# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13c1TZM67YY5Yewaivoux-x7X9Xh70D1w
"""

import streamlit as st
import torch
import matplotlib.pyplot as plt
from cgan_utils import Generator

@st.cache_resource
def load_model():
    model = Generator(100, 10, (1, 28, 28))
    model.load_state_dict(torch.load("cgan_models/generator.pth", map_location="cpu"))
    model.eval()
    return model

st.title("🖋️ Handwritten Digit Generator (0–9)")
digit = st.selectbox("Select a digit to generate:", list(range(10)))

if st.button("Generate 5 Images"):
    model = load_model()
    noise = torch.randn(5, 100)
    labels = torch.tensor([digit]*5)
    with torch.no_grad():
        images = model(noise, labels).view(-1, 28, 28)
        images = (images + 1) / 2  # Normalize to [0,1]

    cols = st.columns(5)
    for i in range(5):
        cols[i].image(images[i].numpy(), width=80, clamp=True, channels="GRAY")